export const events = [
  {
    image: "/images/event1.png",
    title: "Dev Launch Conference 2025",
    slug: "dev-launch-conference-2025",
    location: "Seattle, WA",
    date: "February 10, 2025",
    time: "10:00 AM – 4:00 PM",
  },
  {
    image: "/images/event2.png",
    title: "Next.js Conf 2025",
    slug: "nextjs-conf-2025",
    location: "San Francisco, CA",
    date: "March 12, 2025",
    time: "9:00 AM – 5:00 PM",
  },
  {
    image: "/images/event3.png",
    title: "Global AI Summit",
    slug: "global-ai-summit",
    location: "London, UK",
    date: "April 22–24, 2025",
    time: "All Day",
  },
  {
    image: "/images/event4.png",
    title: "JS World Conference",
    slug: "js-world-conference",
    location: "Amsterdam, Netherlands",
    date: "May 8–9, 2025",
    time: "10:00 AM – 6:00 PM",
  },
  {
    image: "/images/event5.png",
    title: "Cloud Engineering Expo",
    slug: "cloud-engineering-expo",
    location: "New York, USA",
    date: "July 3, 2025",
    time: "8:30 AM – 4:30 PM",
  },
  {
    image: "/images/event6.png",
    title: "Open Source Innovation Summit",
    slug: "open-source-innovation-summit",
    location: "Berlin, Germany",
    date: "August 19, 2025",
    time: "9:30 AM – 5:30 PM",
  },
];
